// Copyright (c) 2025-present databayt
// Licensed under MIT -- see LICENSE for details

/**
 * `curricula/index.json` — the one file a consumer reads to discover
 * everything: every curriculum, its grades, and each subject with its counts
 * and which assets exist. Published to `catalog/index.json` on the CDN.
 *
 * Deterministic (no timestamps), so it only changes when the catalog does.
 *   pnpm index           write it
 *   pnpm index --check   fail if it is stale (CI)
 */

import { existsSync, readdirSync, readFileSync, statSync, writeFileSync } from "node:fs"
import { join } from "node:path"

import type { Curriculum, Exams, QBank, Structure } from "../schema/index.ts"
import { CONTENT_ROOT } from "../src/paths.ts"
import { gradeOrder } from "./lib/vocab.ts"

const REPO = join(import.meta.dirname, "..")
const ROOT = join(REPO, CONTENT_ROOT)
const OUT = join(ROOT, "index.json")

const lock: Record<string, unknown> = JSON.parse(
  readFileSync(join(REPO, "assets.lock.json"), "utf8")
).assets
const locked = (key: string) => key in lock
const read = <T>(p: string): T => JSON.parse(readFileSync(p, "utf8")) as T
const dirs = (p: string) =>
  readdirSync(p).filter((n) => !n.startsWith(".") && statSync(join(p, n)).isDirectory())

function assessments(dir: string) {
  let questions = 0
  let exams = 0
  const walk = (d: string) => {
    if (existsSync(join(d, "qbank.json")))
      questions += read<QBank>(join(d, "qbank.json")).questions.length
    if (existsSync(join(d, "exams.json"))) exams += read<Exams>(join(d, "exams.json")).exams.length
    for (const n of dirs(d)) if (/^\d{2}-/.test(n)) walk(join(d, n))
  }
  walk(dir)
  return { questions, exams }
}

const curricula = dirs(ROOT)
  .sort()
  .map((cur) => {
    const c = read<Curriculum>(join(ROOT, cur, "curriculum.json"))
    const grades = dirs(join(ROOT, cur))
      .sort((a, b) => gradeOrder(a) - gradeOrder(b))
      .map((grade) => ({
        id: grade,
        subjects: dirs(join(ROOT, cur, grade))
          .sort()
          .map((subject) => {
            const dir = join(ROOT, cur, grade, subject)
            const s = read<Structure>(join(dir, "structure.json"))
            const base = `catalog/${cur}/${grade}/${subject}`
            const pages = Object.keys(lock).filter((k) => k.startsWith(`${base}/pages/`)).length
            const pagesMd = existsSync(join(dir, "pages-md"))
              ? readdirSync(join(dir, "pages-md")).filter((f) => /^\d+\.md$/.test(f)).length
              : 0
            return {
              id: s.id,
              subject,
              title: s.title,
              lang: s.lang,
              status: s.status,
              concept: s.concept,
              publisher: s.source.publisher,
              chapters: s.chapters.length,
              lessons: s.chapters.reduce((n, ch) => n + ch.lessons.length, 0),
              ...assessments(dir),
              assets: {
                textbook: locked(`${base}/textbook.pdf`),
                markdown: existsSync(join(dir, "textbook.md")),
                cover: locked(`${base}/cover.jpg`),
                thumbnail: locked(`${base}/thumbnail.jpg`),
                banner: locked(`${base}/banner.jpg`),
                pages,
                pagesMd,
              },
            }
          }),
      }))
    return { id: c.id, title: c.title, country: c.country, lang: c.lang, grades }
  })

const totals = { curricula: curricula.length, subjects: 0, chapters: 0, lessons: 0, questions: 0 }
for (const c of curricula)
  for (const g of c.grades)
    for (const s of g.subjects) {
      totals.subjects++
      totals.chapters += s.chapters
      totals.lessons += s.lessons
      totals.questions += s.questions
    }

const index = { $comment: "Generated by `pnpm index`. Do not edit.", totals, curricula }
const text = JSON.stringify(index, null, 1) + "\n"

if (process.argv.includes("--check")) {
  if (!existsSync(OUT) || readFileSync(OUT, "utf8") !== text) {
    console.error("curricula/index.json is stale — run `pnpm index`")
    process.exit(1)
  }
  console.log("✓ index is current")
} else {
  writeFileSync(OUT, text)
  console.log(`index: ${JSON.stringify(totals)}`)
}
